# Generated by Django 4.1.3 on 2022-11-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('director', models.CharField(max_length=128)),
                ('synopsis', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
