# Generated by Django 4.1.3 on 2022-11-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_studio_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='upDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
