# Generated by Django 4.1.3 on 2022-11-07 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_movie_date_movie_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='films.hall'),
            preserve_default=False,
        ),
    ]
