# Generated by Django 4.1.3 on 2022-11-07 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_remove_hall_movie_movie_hall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='countryName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hall',
            old_name='hallName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='studio',
            old_name='studioCuntry',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='studio',
            old_name='studioName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='films.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='studio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='films.studio'),
            preserve_default=False,
        ),
    ]
