# Generated by Django 4.1.3 on 2022-11-09 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_alter_movie_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='note',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
